- src/sass/utils/reset.scss
> Base styles

- src/index.html
- src/modal.js
- src/partials/modal.html
- src/partials/modals/buy-now.html
- src/partials/modals/franchise.html
- src/partials/modals/ingridients.html
- src/partials/modals/our-location.html
- src/partials/modals/read-more.html
- src/sass/components/_components.scss
- src/sass/components/_modal.scss
- src/sass/utils/_vars.scss
Прокрутку вікна, якщо в нього Height більша за вьюпорт, реалізувати в такій спосіб, як я робив в домашці не вийшло. Заважає:
по-перше те, що тут не фіксована висота вікна, через це я не можу зробити медіа запит, який би примінив необхідні стилі в потрібний момент,
по-друге те, що тут пропонується використовувати один бекдроп оверлей на всі вікна.
> Modal window general

- src/partials/modal.html
Тепер буде відкриватись у вьюпорті, незалежно від поточної позиції скролу
> Fix modal open position

- src/modal.js
- src/sass/components/_modal.scss
Додав, щоб сторінка не скролилася, коли відкрите модальне вікно
> Prevent body scroll when modal windows is shown

- src/partials/modals/franchise.html
- src/partials/modals/ingridients.html
- src/sass/components/_components.scss
- src/sass/components/_form.scss
Форму додав до модалки Franchise. Звідти її можна копіювати в інші модалки.
> Form general

- src/partials/about.html
- src/sass/layout/_about.scss
Виправила:
- нижній паддінг
- забрала закомічений код
- застосувала міксіни
- вирівняла кнопку для моб версії
- ніби нічого не забула)))
> section about done

- src/sass/layout/_advantages.scss
З ширинами ще не розібралась, поки лишається з додатковими падінгами на контейнері.
> added retina photos in section advantages

- src/sass/components/_form.scss
- src/sass/components/_modal.scss
Змінив колір фокусу на зелений, як у кнопки, на хрестику модалки та на бордеру інпуту форми
> Change form input focus color to green

- src/partials/modals/buy-now.html
- src/sass/layout/modals/_modal-buy-now.scss
Переглянь, можливо побачиш помилки, ще не готова, буду ще доробляти, просто щоб було що обговорити ввечері. Сподіваюсь конфліктів не буде бо працювалла в старій версії
> Modal buy-now on 85% ready

- src/partials/button.html
- src/sass/components/_button.scss
- src/sass/utils/_vars.scss
> fix small bugs

- src/sass/components/_form.scss
- src/sass/components/_modal.scss
Поправив ширину форми та тайтлу модалки на таблеті,
Поправив шрифти
> Fix form width on tablet

- src/sass/components/_icon.scss
> зміни по бему 

- src/partials/modals/ingridients.html
- src/sass/layout/modals/_modal-ingridients.scss
Завершила модалку, необхідно лише пофіксити максимальну ширину форм
> Ingredients modal

- src/partials/products.html
- src/sass/components/_button.scss
- src/sass/layout/_products.scss
minimized transition, added animation time to the arrow in the button, little reworked BEM, rechecked styles, tweaked shadow color and optimized code
> fix bugs button and products

- src/partials/about.html
- src/sass/layout/_about.scss
Тільки виправлення по секції бо форму повністю зламала(((
> Only about

- src/partials/about.html
- src/sass/layout/_about.scss
> add  paddings

- src/partials/about.html
> Виправила id що поламала(((

- src/sass/layout/_about.scss
Виправила падінги бо на швидкоруч після роботи получилась якась фігня, додала шрифти бо в боді напевно щось змінювалось після чого на десктопі і таблеті працювало не ок.
> final correct

- src/partials/products.html
- src/sass/layout/_products.scss
adds rubbery styles in mobile version products section and hangs on button modal ingredients
> fixed bugs in products

- src/partials/footer.html
- src/sass/layout/_footer.scss
Старая ветка footer забагалась, не могу сделать нормально Fetch, footer2 последняя актуальная версия
> upd html/css footer

- src/partials/modal.html
- src/sass/layout/modals/_modal-franchise.scss
Перевірив, що модалки вірно відкриваются з кнопок на сторінці.
Видалив тестові кнопки для модалок внизу сторінки.
> Remove modal test buttons

- src/partials/modals/buy-now.html
- src/partials/modals/franchise.html
Видалив з форм зайві айдішніки
> Remove form redundant id

- src/sass/layout/_advantages.scss
Передивилась сітку. Додала space-berween для десктопа.
> justify-content fixed

- src/sass/layout/_customer-reviews.scss
> Border-radius

- src/partials/modals/buy-now.html
- src/partials/modals/franchise.html
- src/partials/modals/ingridients.html
- src/partials/modals/ingridients2.html
- src/partials/modals/ingridients3.html
- src/partials/modals/our-location.html
- src/partials/modals/read-more.html
- src/sass/components/_modal.scss
Пофіксив розмір кнопки закриття модалки згідно з макетом.
Довелося видалити width і height з html усіх модалок, в деяких модалках спрацював prettier не лякайся.
Також додав бордер до кнопки закриття при ховері, подивись.
> Fix modal close button small size

- src/partials/about.html
- src/partials/advantages.html
- src/partials/footer.html
- src/partials/hero-header.html
- src/sass/components/_container.scss
Зроблю пул реквест про всяк випадок
> Add radius to sections corners

- src/partials/modals/buy-now.html
- src/partials/modals/franchise.html
Видалив атрібут autofocus з інпутів.
> Remove forms input autofocus

- src/partials/modals/franchise.html
> Fix email validation pattern

- src/partials/contacts.html
> Fix tel in a href
